baseurl: "https://iwesep2019.github.io/"
title: "IWESEP 2019"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "IWESEP 2019"
  Description: "The 10th International Workshop on Empirical Software Engineering in Practice"
  Date: "December 13-14, 2019"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Nishiwaseda Campus of Waseda University"
  Address: "3-4-1 Ookubo, Shinjuku-ku, Tokyo, 169-8555, JAPAN"
  City:  "Tokyo"
  State: "Japan"
  # Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - important
    - cfp
    - venue
    - speakers
    # - program
    - organization
    - sponsors
    # - partners
    - previous
    # - contact

  # Titles which you can translate to other languages
  Titles:
    about: "IWESEP 2019"
    important: "Important Dates"
    cfp: "Call for Papers"
    venue: "Venue"
    speakers: "Special Talk"
    program: "Program"
    organization: "Organization"
    sponsors: "Sponsors"
    partners: "Partners"
    previous: "Previous"
    contact: "Contact"

  # List of Important Days
  Important:
    - name: "Abstract submission"
      date: "September 27th, 2019 (AOE) (extended)"
      done: true
    - name: "Research paper submission"
      date: "October 4th, 2019 (AOE) (extended)"
      done: true
    - name: "Notifications"
      date: "November 1st, 2019 (AOE)"
      done: false
    - name: "Camera Ready"
      date: "November 8th, 2019 (AOE)"
      done: false
    - name: "Abstract submission (Poster)"
      date: "November 5th, 2019 (AOE)"
      done: false
    - name: "Notifications (Poster)"
      date: "November 10th, 2019 (AOE)"
      done: false

  # List of Previous Editions
  Previous:
    - name: "IWESEP 2018"
      url: "https://iwesep2018.github.io/"
    - name: "IWESEP 2017"
      url: "https://iwesep2017.github.io/"
    - name: "IWESEP 2016"
      url: "https://iwesep2016.github.io/"
    - name: "IWESEP 2014"
      url: "https://iwesep2014.github.io/"
    - name: "IWESEP 2013"
      url: "https://sites.google.com/site/iwesep2013/home"
    - name: "IWESEP 2012"
      url: "https://sites.google.com/site/iwesep2012/home"
    - name: "IWESEP 2011"
      url: "https://sites.google.com/site/iwesep2011/home"
    - name: "IWESEP 2010"
      url: "https://iwesep.wordpress.com/"
    - name: "IWESEP 2009"
      url: "http://sdlab.naist.jp/IWESEP2009/organization.html"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Register now!"
  #   link: "https://easychair.org/conferences/?conf=iwesep2019"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Global Software Engineering Laboratory, Waseda University"
      url: "https://www.waseda.jp/inst/gcs/en/labo/globalsoftware/"
    - name: "Nara Institute of Science and Technology"
      url: "http://www.naist.jp/en/"
    # - name: "Hugo"
    #   logo: "/img/hugo.png"
    #   url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # List of Organization
  Organization:
    - role: "General"
      chair: true
      member:
        - name: "Keisuke Hotta"
          affiliation: "FUJITSU LABORATORIES LTD."
        - name: "Takao Nakagawa"
          affiliation: "FUJITSU LABORATORIES LTD."
        - name: "Kazuhiro Yamashita"
          affiliation: "FUJITSU LABORATORIES LTD."
    - role: "PC"
      chair: true
      member:
        - name: "Akinori Ihara"
          url: "http://web.wakayama-u.ac.jp/~ihara/"
          affiliation: "Wakayama University"
        - name: "Marco Aurélio Gerosa"
          url: "http://www.ime.usp.br/~gerosa"
          affiliation: "Northern Arizona University"
    - role: "Publication"
      chair: true
      member:
        - name: "Masanari Kondo"
          url: "https://se.is.kit.ac.jp/portfolio/m-kondo/"
          affiliation: "Kyoto Institute of Technology"
        - name: "Dong Wang"
          affiliation: "Nara Institute of Science and Technology"
    - role: "Registration"
      chair: true
      member:
        - name: "Tomomi Hatano"
          affiliation: "FUJITSU LABORATORIES LTD."
        - name: "Yuki Ueda"
          affiliation: "Nara Institute of Science and Technology"
    - role: "Finance"
      chair: true
      member:
        - name: "Hideaki Hata"
          url: "https://hideakihata.github.io/"
          affiliation: "Nara Institute of Science and Technology"
    - role: "Publicity"
      chair: true
      member:
        - name: "Hiroyuki Kirinuki"
          affiliation: "NTT"
        - name: "Gustavo Ansaldi Oliva"
          url: "http://www.gaoliva.com/"
          affiliation: "Queen's University"
    - role: "Web"
      chair: true
      member:
        - name: "Haruki Yokoyama"
          affiliation: "FUJITSU LABORATORIES LTD."
    - role: "Local Arrangement"
      chair: true
      member:
        - name: "Kunihiro Noda"
          affiliation: "FUJITSU LABORATORIES LTD."
        - name: "Kazuya Aizawa"
          affiliation: "Waseda University"
    - role: "Steering Committee Members"
      chair: false
      member:
        - name: "Akinori Ihara"
          url: "http://web.wakayama-u.ac.jp/~ihara/"
          affiliation: "Wakayama University"
        - name: "Hideaki Hata"
          url: "https://hideakihata.github.io/"
          affiliation: "Nara Institute of Science and Technology"
        - name: "Masateru Tsunoda"
          url: "http://www.info.kindai.ac.jp/~tsunoda/index-e.html"
          affiliation: "Kindai University"
        - name: "Raula Gaikovina Kula"
          url: "https://raux.github.io/"
          affiliation: "Nara Institute of Science and Technology"
        - name: "Shinsuke Matsumoto"
          url: "http://sdl.ist.osaka-u.ac.jp/~shinsuke/"
          affiliation: "Osaka University"
        - name: "Yasutaka Kamei"
          url: "http://posl.ait.kyushu-u.ac.jp/~kamei/"
          affiliation: "Kyushu University"
        - name: "Eunjong Choi"
          url: "https://se.is.kit.ac.jp/portfolio/eunjong_choi/"
          affiliation: "Kyoto Institute of Technology"
    - role: "Advisory Committee Members"
      chair: false
      member:
        - name: "Katsuro Inoue"
          url: "http://sel.ist.osaka-u.ac.jp/people/inoue/"
          affiliation: "Osaka University"
        - name: "Shinji Kusumoto"
          url: "https://sdl.ist.osaka-u.ac.jp/~kusumoto/index-e.htm"
          affiliation: "Osaka University"
        - name: "Kenichi Matsumoto"
          url: "http://isw3.naist.jp/~matumoto/"
          affiliation: "Nara Institute of Science and Technology"
    - role: "Program Committee Members"
      chair: false
      member:
        - name: "Sousuke Amasaki"
          url: "https://gdata.oka-pu.ac.jp/profile/ja.0970d97d84699711f2878e419aae6ccb.html"
          affiliation: "Okayama Prefectural University"
        - name: "Shinpei Hayashi"
          url: "http://www.se.cs.titech.ac.jp/~hayashi/index.html.en"
          affiliation: "Tokyo Institute of Technology"
        - name: "Yoshiki Higo"
          url: "http://sdl.ist.osaka-u.ac.jp/~higo/wordpress/"
          affiliation: "Osaka University"
        - name: "Shin Hong"
          url: "http://hongshin.github.io/"
          affiliation: "Handong Global University"
        - name: "Foutse Khomh"
          url: "http://www.khomh.net/"
          affiliation: "DGIGL, École Polytechnique de Montréal"
        - name: "Raula Gaikovina Kula"
          url: "https://raux.github.io/"
          affiliation: "Nara Institute of Science and Technology"
        - name: "Yepang Liu"
          url: "https://yepangliu.github.io/"
          affiliation: "Southern University of Science and Technology"
        - name: "David Lo"
          url: "http://www.mysmu.edu/faculty/davidlo/"
          affiliation: "Singapore Management University"
        - name: "Yuki Manabe"
          url: "http://www.dbms.cs.kumamoto-u.ac.jp/~y-manabe/index_en.html"
          affiliation: "Kumamoto University"
        - name: "Shane Mcintosh"
          url: "http://shanemcintosh.org/"
          affiliation: "McGill University"
        - name: "Osamu Mizuno"
          url: "https://se.is.kit.ac.jp/~o-mizuno/"
          affiliation: "Kyoto Institute of Technology"
        - name: "Passakorn Phannachitta"
          url: "https://dblp.org/pers/hd/p/Phannachitta:Passakorn"
          affiliation: "College of Arts, Media and Technology, Chiang Mai University"
        - name: "Christoph Treude"
          url: "http://ctreude.ca/"
          affiliation: "The University of Adelaide"
        - name: "Thomas Zimmermann"
          url: "https://www.microsoft.com/en-us/research/people/tzimmer/"
          affiliation: "Microsoft"
        - name: "Tetsuya Kanda"
          url: "http://www.tetsuyakanda.jp/"
          affiliation: "Osaka University"
        - name: "Kiyoshi Honda"
          # url: ""
          affiliation: "Osaka Institute of Technology"

  # The entire program
  Program:
    - name: "Dr. Mukul Prasad"
      photo: "/img/Mukul-Prasad.jpg"
      bio: "Dr. Mukul Prasad is a Director in the Advanced Software & Algorithms Laboratory at Fujitsu Laboratories of America. His team's research aims to develop automated tools and methodologies to empower software development teams to be more productive and to develop more correct and reliable software. He has thrice been a co-recipient of the Fujitsu Laboratories President Award for innovation. ​ He has authored over 50 conference and journal papers, including 1 best paper award and 2 best paper nominations, 1 book, and holds over 50 patents. He has served on more than 20 technical program committees of international conferences and workshops. ​ He has a Ph.D. from the University of California at Berkeley and a B.Tech from the Indian Institute of Technology at Delhi. He is a Senior Member of ACM and a Senior Member of IEEE."
      company: "Director in the Advanced Software & Algorithms Laboratory at Fujitsu Laboratories of America"
      link:
        href: "https://www.fujitsu.com/us/about/businesspolicy/tech/rd/research-staff/mukul-prasad.html"
        text: "website"
      presentation:
        title: "Intelligence-Driven Software Engineering"
        description: "The present-day system of developing and distributing software relies on a sophisticated ecosystem of repositories that catalog virtually every aspect and every kind of artifact of a software's lifecycle. They include version control systems for source code, to bug tracking systems, to online developer and user discussion forums. These repositories, commonly referred to as Big Code, encapsulate vast amounts of human software development expertise, experience, and opinions. This has motivated a burgeoning field of research within software engineering that uses Artificial Intelligence (AI) technologies, such as machine learning, to mine Big Code for relevant insights, i.e., \"intelligence\", and use it to power next-generation software engineering solutions. In this talk I will provide an overview of research conducted at Fujitsu Laboratories of America, in the area of intelligence-driven software engineering, in the context of the larger body of work in this upcoming area. In particular, I will discuss our research in the areas of automated testing, debugging and patching, as well as our efforts to translate this research into practical solutions to help real users to be more productive and to develop more correct and reliable software."
    - name: "Dr. Fabio Palomba"
      photo: "/img/Fabio-Palomba.jpg"
      bio: "Fabio Palomba is an Assistant Professor of Software Engineering at the University of Salerno, Italy. He received the European PhD degree in Management & Information Technology in 2017. His PhD Thesis was the recipient of the 2017 IEEE Computer Society Best PhD Thesis Award (Italy section). His research interests include software maintenance and evolution, software testing, empirical software engineering, source code quality, and mining software repositories. He was the recipient of two ACM/SIGSOFT and one IEEE/TCSE Distinguished Paper Awards at ASE'13, ICSE'15, and ICSME'17, respectively, and Best Paper Awards at CSCW'18 and SANER'18. In 2019 he was the recipient of an SNSF Ambizione grant, one of the most prestigious individual research grants in Europe. He serves and has served as a program committee member of various international conferences (e.g., MSR, ICPC, ICSME), and as referee for various international journals (e.g., TSE, EMSE, JSS) in the field of software engineering. Fabio will be the program co-chair of ICPC 2021, which will be held in Madrid, Spain. Since 2016 he is Review Board Member of EMSE and, since 2019, Editorial Board Member of TOSEM, JSS, and SCICO. He was the recipient of five Distinguished/Outstanding Reviewer Awards for his reviewing activities conducted for EMSE, IST, and JSS between 2015 and 2019."
      company: "Senior Research Associate at the Zurich Empirical Software Engineering Team (ZEST) of the University of Zurich"
      link:
        href: "https://dibt.unimol.it/staff/fpalomba/"
        text: "website"
      presentation:
        title: "Test code quality: A New Measure of Test Code Effectiveness"
        description: "Test cases form the first line of defense against the introduction of software faults. In the past, researchers have been studying methods and tools to support developers during testing activities, mainly focusing on how to (1) measure the capabilities of test cases in finding real defects in production code and (2) provide them with automatically written tests. Despite this notable effort, the impact of test code quality has been mostly ignored. In this talk, I will show that this aspect has a critical impact on the effectiveness of tests and, particularly, on the presence of flaky tests as well as on the code coverage achievable by test cases automatically generated. Furthermore, I will discuss how test code quality can be employed for predictive analytics and assist developers when assessing test code effectiveness."

    # - name: "Check-in / Breakfast"
    #   time: "9h00"

    # - name: "Linus Torvalds"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Linux Foundation"
    #   link:
    #     href: "http://twitter.com/linus"
    #     text: "@linus"
    #   presentation:
    #     title: "Digging into a Linux Kernel"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "10h00"

    # - name: "Bill Gates"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Microsoft"
    #   link:
    #     href: "http://github.com/billy95"
    #     text: "@billy95"
    #   presentation:
    #     title: "Introducing Windows 12"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "11h00"

    # - name: "Lunch"
    #   time: "12h00"

    # - name: "Chuck Norris"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Delta Command"
    #   link:
    #     href: "http://twitter.com/littlechuck"
    #     text: "@littlechuck"
    #   presentation:
    #     title: "How to kill a elephant with one finger"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "13h00"

    # - name: "Steve Jobs"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Apple, Inc."
    #   link:
    #     href: "http://github.com/stevie"
    #     text: "@stevie"
    #   presentation:
    #     title: "Presenting iPad"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "14h00"

    # - name: "Coffee-break"
    #   time: "15h00"

    # - name: "Mark Zuckerberg"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Facebook"
    #   link:
    #     href: "http://twitter.com/zuck"
    #     text: "@zuck"
    #   presentation:
    #     title: "Revealing Facebook Secrets"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "16h00"

    # - name: "Steve Wozniak"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Apple, Inc."
    #   link:
    #     href: "http://twitter.com/woz"
    #     text: "@woz"
    #   presentation:
    #     title: "Why do I prefer Android over iPhone"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "17h00"
