baseurl = "https://iwesep2019.github.io/"
languageCode = "en-us"
title = "IWESEP 2019"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/iwesep"
  twitter = "https://twitter.com/iwesep"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  custom_css = ["/css/custom.css"]